modLoader = "javafml"
loaderVersion = "[${forgeshortversion},)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbchunks"
version = "${version}"
displayName = "FTB Chunks"
authors = "FTB Team"
description = '''
Claim chunks to protect your base from griefers!
'''
# logoFile="logo.png"
license = "All Rights Reserved"

[[dependencies.ftbchunks]]
modId = "forge"
mandatory = true
versionRange = "[${forgeversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "architectury"
mandatory = true
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "ftblibrary"
mandatory = true
versionRange = "[${libraryversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "ftbteams"
mandatory = true
versionRange = "[${teamsversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "ftbranks"
mandatory = false
versionRange = "[${ranksversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "kubejs"
mandatory = false
versionRange = "[${kubejsversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "luckperms"
mandatory = false
versionRange = "[5.4.46,)"
ordering = "AFTER"
side = "SERVER"