modLoader = "javafml"
loaderVersion = "[28,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Chunks/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbchunks"
version = "${version}"
displayName = "FTB Chunks"
authors = "LatvianModder"
description = '''
Claim chunks to protect your base from griefers!
'''
# logoFile="logo.png"
license = "All Rights Reserved"

[[dependencies.ftbchunks]]
modId = "forge"
mandatory = true
versionRange = "[28,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.14,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "architectury"
mandatory = true
versionRange = "[1.20.28,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1605.3.1-build.53,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "ftbteams"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbchunks]]
modId = "kubejs"
mandatory = false
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"
