image: java:8-jdk
stages:
  - build
  - release

# Build and publish public releases to maven
build_release:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew clean build publish
  artifacts:
    paths:
      - build/libs/*.jar
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_ID == "151"'

# Build development versions
build_dev:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew clean build publish
  artifacts:
    paths:
      - builds/libs/*.jar
  rules:
    - if: '$CI_PROJECT_ID == "138"'

# If we're on the public facing repo and there's a commit tag, publish to CurseForge
curseforge_release:
  stage: release
  script:
    - chmod +x gradlew
    - ./gradlew curseforgePublish
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_ID == "151"'
  needs:
    - job: build_release
      artifacts: true
